### PR TITLE
Strip unneeded files, structures, packages and dependencies.

### PR DESCRIPTION
**Pull request by evanlinjin**

### CODE REVIEW

**Comment by SkycoinSynth** [comment]
1> This is a single commit.

2> If viper was removed, there should be a commit "viper removed". In the pull request.

3> If integration tests were deleted, there should be an individual commit "Deleted integration tests folder"

4> If docker images for integration test were deleted, there should be a commit "deleted docker images folder".

Why is viper removal ticket tagged in this pull request if there is no commit labelled for viper removal?

**Comment by SkycoinSynth** [comment]
There is no description on this pull request.

**Comment by evanlinjin** [comment]
> There is no description on this pull request.

Done.

**Comment by evanlinjin** [comment]
> 1> This is a single commit.
> 
> 2> If viper was removed, there should be a commit "viper removed". In the pull request.
> 
> 3> If integration tests were deleted, there should be an individual commit "Deleted integration tests folder"
> 
> 4> If docker images for integration test were deleted, there should be a commit "deleted docker images folder".
> 
> 5> If there were modifications to the make file, there should be an individual commit with the modifications to the make file and the commit description should state that the make file was modified.
> 
> Why is viper removal ticket tagged in this pull request if there is no commit labelled for viper removal?

I apologize about this. I will make sure my commit messages are more descriptive for future commits.

**Pull request merged**
